name: LunarClient-API
version: ${pluginVersion}
description: ${pluginDescription}
author: ${pluginAuthor}
main: com.lunarclient.bukkitapi.LunarClientAPI
load: STARTUP
api-version: 1.13
softdepend:
  - LuckPerms
website: https://github.com/powercasgamer/LunarClientAPI
